- hosts: 'workers, masters'
  become: yes

  tasks:
    - name: create the root user account
      user: name=root append=yes state=present createhome=yes shell=/bin/bash

    - name: allow 'root' to use sudo without needing a password
      lineinfile:
        dest: /etc/sudoers
        line: 'root ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: set up authorized keys for the root user
      authorized_key: user=root key="{{item}}"
      with_file:
        - ~/.ssh/id_rsa.pub